services:
  - type: web
    name: BuzzyBeeFrontendApp
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://graph-vis-be.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
